### ISSUE TITLE
Fix contrast of highlighted nav when tab navigating

### ISSUE THREAD

**Issue by mauromsl** [BirkbeckCTP/clean#6]
When tab navigating the navbar, the text becomes white over white background, making it unreadable 

WCAG 1.4.1
WCAG 2.4.7
![image](https://user-images.githubusercontent.com/10760678/93992783-e274bb00-fd85-11ea-9318-4fae3f324f7d.png)

**Comment by ajrbyers** [comment]
Fixed by 575fa84..9bcba87 on Bitbucket.
