### ISSUE TITLE
HTML lang attribute is hardcoded to english

### ISSUE THREAD

**Issue by mauromsl** [BirkbeckCTP/clean#8]
It should pull the language from the request object programatically

WCAG 3.1.1

**Comment by ajrbyers** [comment]
I think this was also fixed in #10.

```
{% load static %}
<!DOCTYPE html>
<html lang="{{ settings.LANGUAGE_CODE }}">
<head>
```

**Comment by ajrbyers** [comment]
Ah no - Im wrong :D

**Comment by mauromsl** [comment]
Yeah, it needs to pull the current language from the request context, but given that we don't have any non-english sites using this theme we are fine for now

**Comment by ajrbyers** [comment]
Django has `{% get_current_language as current_language %}`
